### ISSUE TITLE
ICARUS bug - math bug

### ISSUE THREAD

**Issue by nab622** [ParabolicMinds/Parabolic-Realms#9]
When setting a variable's value to +1 or -1, it is supposed to increment or decrement the variable. However, when using it on a SET_PARM, it glitches and corrupts all SET_PARMs on that entity. I know ICARUS is dated, but this still needs fixed.

**Comment by cagelight** [comment]
This was definitely fixed by OpenJK, I remember looking into that.

**Comment by nab622** [comment]
How wude.
